spring.application.name=metro
# PostgreSQL DB config
spring.datasource.url=jdbc:postgresql://localhost:5432/metrodb
spring.datasource.username=postgres
spring.datasource.password=123

# Hibernate JPA auto update
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# JWT settings - REPLACE the secret with a long random string in production
app.jwt.secret=mySuperSecretKeyThatIsAtLeast64CharactersLongForHS256
app.jwt.expiration-ms=3600000

# CORS - allow your frontend origin(s)
app.cors.allowed-origins=http://localhost:3000

